services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000"
